# Generated by Django 5.0.1 on 2026-02-17 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title', max_length=300)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=300, unique=True)),
                ('category', models.CharField(choices=[('pcos_types', 'PCOS Types'), ('diet', 'Diet & Nutrition'), ('lifestyle', 'Lifestyle & Exercise'), ('research', 'Research & Science'), ('mental_health', 'Mental Health'), ('symptoms', 'Symptoms & Management'), ('faq', 'Frequently Asked Questions')], help_text='Article category', max_length=50)),
                ('content', models.TextField(help_text='Article content in Markdown format')),
                ('summary', models.TextField(blank=True, help_text='Short summary for article cards')),
                ('author', models.CharField(default='OvaSense Team', help_text='Article author', max_length=200)),
                ('read_time_minutes', models.IntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Optional thumbnail image URL')),
                ('published', models.BooleanField(default=True, help_text='Whether article is published and visible')),
                ('publish_date', models.DateField(auto_now_add=True, help_text='Publication date')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0, help_text='Number of times article has been viewed')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_gap_days', models.IntegerField(help_text='Days between menstrual cycles')),
                ('periods_regular', models.BooleanField(blank=True, help_text='Are periods regular?', null=True)),
                ('longest_cycle_gap_last_year', models.IntegerField(blank=True, help_text='Longest gap between periods in last 12 months', null=True)),
                ('acne', models.BooleanField(blank=True, default=None, help_text='Presence of acne', null=True)),
                ('hair_loss', models.BooleanField(blank=True, default=None, help_text='Hair thinning or loss from scalp', null=True)),
                ('facial_hair_growth', models.BooleanField(blank=True, help_text='Excessive facial or body hair (hirsutism)', null=True)),
                ('dark_patches', models.BooleanField(blank=True, default=None, help_text='Dark patches on skin (acanthosis nigricans)', null=True)),
                ('sugar_cravings', models.BooleanField(blank=True, default=None, help_text='Experiencing sugar cravings', null=True)),
                ('weight_gain', models.BooleanField(blank=True, default=None, help_text='Unexplained weight gain or difficulty losing weight', null=True)),
                ('waist_cm', models.IntegerField(blank=True, help_text='Waist circumference in cm', null=True)),
                ('family_diabetes_history', models.BooleanField(blank=True, help_text='Family history of diabetes', null=True)),
                ('fatigue_after_meals', models.BooleanField(blank=True, help_text='Feeling tired after eating', null=True)),
                ('bmi', models.FloatField(blank=True, help_text='Body Mass Index', null=True)),
                ('stress_level', models.IntegerField(blank=True, help_text='Stress level (1-10)', null=True)),
                ('sleep_hours', models.FloatField(blank=True, help_text='Average sleep hours per night', null=True)),
                ('mood_swings', models.BooleanField(blank=True, default=None, help_text='Mood swings, anxiety, or depression', null=True)),
                ('pill_usage', models.BooleanField(blank=True, default=None, help_text='Recent use of birth control pills', null=True)),
                ('trying_to_conceive', models.BooleanField(blank=True, help_text='Active attempt to conceive', null=True)),
                ('spotting_between_periods', models.BooleanField(blank=True, help_text='Bleeding between periods', null=True)),
                ('heavy_bleeding', models.BooleanField(blank=True, help_text='Excessive menstrual bleeding', null=True)),
                ('severe_pelvic_pain', models.BooleanField(blank=True, help_text='Severe pelvic pain', null=True)),
                ('possible_pregnancy', models.BooleanField(blank=True, help_text='Possibility of pregnancy', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when log was created')),
                ('cycle_irregularity_duration_months', models.IntegerField(blank=True, help_text='How long irregular cycles have persisted (months)', null=True)),
                ('acne_duration_months', models.IntegerField(blank=True, help_text='How long acne has persisted (months)', null=True)),
                ('weight_gain_duration_months', models.IntegerField(blank=True, help_text='How long weight gain has persisted (months)', null=True)),
                ('recent_major_stress_event', models.BooleanField(blank=True, help_text='Major stress event in last 3 months', null=True)),
                ('thyroid_history', models.BooleanField(blank=True, help_text='Personal or family history of thyroid issues', null=True)),
                ('recent_travel_or_illness', models.BooleanField(blank=True, help_text='Recent travel or viral illness', null=True)),
                ('sudden_weight_change', models.BooleanField(blank=True, help_text='Sudden significant weight change (< 3 months)', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhenotypeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenotype', models.CharField(help_text='Classified PCOS phenotype', max_length=100)),
                ('confidence', models.FloatField(help_text='Confidence score (0-100)')),
                ('reasons', models.JSONField(help_text='List of contributing factors')),
                ('data_quality_score', models.IntegerField(default=100, help_text='Data completion/quality score (0-100)')),
                ('rule_version', models.CharField(default='1.0.0', help_text='Version of logic rules used', max_length=20)),
                ('differential_diagnosis', models.CharField(blank=True, help_text='Alternative diagnosis if PCOS is unlikely', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when classification was performed')),
                ('symptom_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.symptomlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CycleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First day of menstruation')),
                ('end_date', models.DateField(blank=True, help_text='Last day of menstruation (optional)', null=True)),
                ('flow_intensity', models.IntegerField(blank=True, help_text='Flow intensity: 1=Very Light, 2=Light, 3=Normal, 4=Heavy, 5=Very Heavy', null=True)),
                ('symptoms', models.JSONField(blank=True, default=list, help_text='List of symptoms during cycle: cramps, bloating, headache, etc.')),
                ('notes', models.TextField(blank=True, help_text='User notes about this cycle')),
                ('predicted', models.BooleanField(default=False, help_text='Whether this was an AI prediction vs actual logged period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who owns this cycle record', on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='api.userprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CycleInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=50)),
                ('cycle_day', models.IntegerField(null=True)),
                ('risk_score', models.IntegerField()),
                ('main_reason', models.TextField()),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of measurement')),
                ('metric_type', models.CharField(choices=[('weight', 'Weight (kg)'), ('sleep', 'Sleep Hours'), ('stress', 'Stress Level (1-10)'), ('acne_severity', 'Acne Severity (1-10)'), ('mood', 'Mood (1-10)'), ('energy', 'Energy Level (1-10)'), ('exercise_minutes', 'Exercise Minutes')], help_text='Type of health metric', max_length=50)),
                ('value', models.FloatField(help_text='Metric value (numeric)')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this metric')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who owns this metric', on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='api.userprofile')),
            ],
            options={
                'ordering': ['-date', 'metric_type'],
                'unique_together': {('user', 'date', 'metric_type')},
            },
        ),
    ]
