# Generated by Django 5.0.1 on 2026-02-15 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_gap_days', models.IntegerField(help_text='Days between menstrual cycles')),
                ('acne', models.BooleanField(default=False, help_text='Presence of acne')),
                ('bmi', models.FloatField(help_text='Body Mass Index')),
                ('stress_level', models.IntegerField(help_text='Stress level on scale 1-10')),
                ('sleep_hours', models.FloatField(help_text='Average hours of sleep per night')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when log was created')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhenotypeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenotype', models.CharField(help_text='Classified PCOS phenotype', max_length=100)),
                ('confidence', models.FloatField(help_text='Confidence score (0-100)')),
                ('reasons', models.JSONField(help_text='List of contributing factors')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when classification was performed')),
                ('symptom_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.symptomlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
