# Generated by Django 5.0.1 on 2026-02-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomlog',
            name='amh_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='chronic_inflammation_symptoms',
            field=models.BooleanField(blank=True, help_text='Joint pain, gut issues, bloating, etc.', null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='exercise_days_per_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='fasting_glucose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='fasting_insulin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='infertility_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='lh_fsh_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='miscarriages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='processed_food_intake',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='testosterone_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='acne',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='acne_duration_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='cycle_irregularity_duration_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='dark_patches',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='facial_hair_growth',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='family_diabetes_history',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='fatigue_after_meals',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='hair_loss',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='heavy_bleeding',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='longest_cycle_gap_last_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='mood_swings',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='periods_regular',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='pill_usage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='possible_pregnancy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='recent_major_stress_event',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='recent_travel_or_illness',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='severe_pelvic_pain',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='sleep_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='spotting_between_periods',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='stress_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='sudden_weight_change',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='sugar_cravings',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='thyroid_history',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='trying_to_conceive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='waist_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='weight_gain',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='weight_gain_duration_months',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
