# Generated by Django 5.0.1 on 2026-02-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomlog',
            name='dark_patches',
            field=models.BooleanField(default=False, help_text='Dark patches on skin (acanthosis nigricans)'),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='hair_loss',
            field=models.BooleanField(default=False, help_text='Hair thinning or loss from scalp'),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='mood_swings',
            field=models.BooleanField(default=False, help_text='Mood swings, anxiety, or depression'),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='pill_usage',
            field=models.BooleanField(default=False, help_text='Recent use of birth control pills'),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='sugar_cravings',
            field=models.BooleanField(default=False, help_text='Experiencing sugar cravings'),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='weight_gain',
            field=models.BooleanField(default=False, help_text='Unexplained weight gain or difficulty losing weight'),
        ),
    ]
