# Generated by Django 5.0.1 on 2026-02-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_symptomlog_amh_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenotyperesult',
            name='data_quality_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
