# Generated by Django 5.0.1 on 2026-02-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_symptomlog_dark_patches_symptomlog_hair_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomlog',
            name='facial_hair_growth',
            field=models.BooleanField(blank=True, help_text='Excessive facial or body hair (hirsutism)', null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='family_diabetes_history',
            field=models.BooleanField(blank=True, help_text='Family history of diabetes', null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='fatigue_after_meals',
            field=models.BooleanField(blank=True, help_text='Feeling tired after eating', null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='heavy_bleeding',
            field=models.BooleanField(blank=True, help_text='Excessive menstrual bleeding', null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='longest_cycle_gap_last_year',
            field=models.IntegerField(blank=True, help_text='Longest gap between periods in last 12 months', null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='periods_regular',
            field=models.BooleanField(blank=True, help_text='Are periods regular?', null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='possible_pregnancy',
            field=models.BooleanField(blank=True, help_text='Possibility of pregnancy', null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='severe_pelvic_pain',
            field=models.BooleanField(blank=True, help_text='Severe pelvic pain', null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='spotting_between_periods',
            field=models.BooleanField(blank=True, help_text='Bleeding between periods', null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='trying_to_conceive',
            field=models.BooleanField(blank=True, help_text='Active attempt to conceive', null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='waist_cm',
            field=models.IntegerField(blank=True, help_text='Waist circumference in cm', null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='acne',
            field=models.BooleanField(blank=True, default=None, help_text='Presence of acne', null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='bmi',
            field=models.FloatField(blank=True, help_text='Body Mass Index', null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='dark_patches',
            field=models.BooleanField(blank=True, default=None, help_text='Dark patches on skin (acanthosis nigricans)', null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='hair_loss',
            field=models.BooleanField(blank=True, default=None, help_text='Hair thinning or loss from scalp', null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='mood_swings',
            field=models.BooleanField(blank=True, default=None, help_text='Mood swings, anxiety, or depression', null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='pill_usage',
            field=models.BooleanField(blank=True, default=None, help_text='Recent use of birth control pills', null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='sleep_hours',
            field=models.FloatField(blank=True, help_text='Average sleep hours per night', null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='stress_level',
            field=models.IntegerField(blank=True, help_text='Stress level (1-10)', null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='sugar_cravings',
            field=models.BooleanField(blank=True, default=None, help_text='Experiencing sugar cravings', null=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='weight_gain',
            field=models.BooleanField(blank=True, default=None, help_text='Unexplained weight gain or difficulty losing weight', null=True),
        ),
    ]
