# Generated by Django 5.0.1 on 2026-02-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_phenotyperesult_data_quality_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phenotyperesult',
            options={},
        ),
        migrations.AddField(
            model_name='phenotyperesult',
            name='ai_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phenotyperesult',
            name='diet_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phenotyperesult',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='phenotyperesult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='phenotyperesult',
            name='data_quality_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phenotyperesult',
            name='differential_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phenotyperesult',
            name='phenotype',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='phenotyperesult',
            name='reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='phenotyperesult',
            name='rule_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
