# Generated by Django 5.0.1 on 2026-02-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_symptomlog_facial_hair_growth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phenotyperesult',
            name='data_quality_score',
            field=models.IntegerField(default=100, help_text='Data completion/quality score (0-100)'),
        ),
        migrations.AddField(
            model_name='phenotyperesult',
            name='differential_diagnosis',
            field=models.CharField(blank=True, help_text='Alternative diagnosis if PCOS is unlikely', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phenotyperesult',
            name='rule_version',
            field=models.CharField(default='1.0.0', help_text='Version of logic rules used', max_length=20),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='acne_duration_months',
            field=models.IntegerField(blank=True, help_text='How long acne has persisted (months)', null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='cycle_irregularity_duration_months',
            field=models.IntegerField(blank=True, help_text='How long irregular cycles have persisted (months)', null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='recent_major_stress_event',
            field=models.BooleanField(blank=True, help_text='Major stress event in last 3 months', null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='recent_travel_or_illness',
            field=models.BooleanField(blank=True, help_text='Recent travel or viral illness', null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='sudden_weight_change',
            field=models.BooleanField(blank=True, help_text='Sudden significant weight change (< 3 months)', null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='thyroid_history',
            field=models.BooleanField(blank=True, help_text='Personal or family history of thyroid issues', null=True),
        ),
        migrations.AddField(
            model_name='symptomlog',
            name='weight_gain_duration_months',
            field=models.IntegerField(blank=True, help_text='How long weight gain has persisted (months)', null=True),
        ),
    ]
