# Generated by Django 4.2 on 2026-02-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_phenotyperesult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phenotyperesult',
            name='future_risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phenotyperesult',
            name='mixed_pcos_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='phenotyperesult',
            name='priority_lifestyle_changes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='phenotyperesult',
            name='recommended_lab_tests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
