# Generated by Django 5.0.1 on 2026-02-16 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_phenotyperesult_data_quality_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title', max_length=300)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=300, unique=True)),
                ('category', models.CharField(choices=[('pcos_types', 'PCOS Types'), ('diet', 'Diet & Nutrition'), ('lifestyle', 'Lifestyle & Exercise'), ('research', 'Research & Science'), ('mental_health', 'Mental Health'), ('symptoms', 'Symptoms & Management'), ('faq', 'Frequently Asked Questions')], help_text='Article category', max_length=50)),
                ('content', models.TextField(help_text='Article content in Markdown format')),
                ('summary', models.TextField(blank=True, help_text='Short summary for article cards')),
                ('author', models.CharField(default='OvaSense Team', help_text='Article author', max_length=200)),
                ('read_time_minutes', models.IntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Optional thumbnail image URL')),
                ('published', models.BooleanField(default=True, help_text='Whether article is published and visible')),
                ('publish_date', models.DateField(auto_now_add=True, help_text='Publication date')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0, help_text='Number of times article has been viewed')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.CharField(help_text='Unique user identifier', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text="User's name", max_length=200)),
                ('age', models.IntegerField(blank=True, help_text="User's age", null=True)),
                ('height_cm', models.FloatField(blank=True, help_text='Height in centimeters', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='User preferences: notifications, theme, etc.')),
                ('last_phenotype', models.CharField(blank=True, help_text='Last PCOS phenotype assessment result', max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CycleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First day of menstruation')),
                ('end_date', models.DateField(blank=True, help_text='Last day of menstruation (optional)', null=True)),
                ('flow_intensity', models.IntegerField(blank=True, help_text='Flow intensity: 1=Very Light, 2=Light, 3=Normal, 4=Heavy, 5=Very Heavy', null=True)),
                ('symptoms', models.JSONField(blank=True, default=list, help_text='List of symptoms during cycle: cramps, bloating, headache, etc.')),
                ('notes', models.TextField(blank=True, help_text='User notes about this cycle')),
                ('predicted', models.BooleanField(default=False, help_text='Whether this was an AI prediction vs actual logged period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who owns this cycle record', on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='api.userprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of measurement')),
                ('metric_type', models.CharField(choices=[('weight', 'Weight (kg)'), ('sleep', 'Sleep Hours'), ('stress', 'Stress Level (1-10)'), ('acne_severity', 'Acne Severity (1-10)'), ('mood', 'Mood (1-10)'), ('energy', 'Energy Level (1-10)'), ('exercise_minutes', 'Exercise Minutes')], help_text='Type of health metric', max_length=50)),
                ('value', models.FloatField(help_text='Metric value (numeric)')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this metric')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who owns this metric', on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='api.userprofile')),
            ],
            options={
                'ordering': ['-date', 'metric_type'],
                'unique_together': {('user', 'date', 'metric_type')},
            },
        ),
    ]
