# Generated by Django 4.2 on 2026-02-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to='api.userprofile'),
        ),
    ]
