"""
PDF report generation for PCOS phenotype results.
"""
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from io import BytesIO
from datetime import datetime


def generate_pdf_report(symptom_log, phenotype_result):
    """
    Generate a PDF report for a symptom log and its classification result.
    
    Args:
        symptom_log: SymptomLog instance
        phenotype_result: PhenotypeResult instance
        
    Returns:
        BytesIO: PDF file in memory
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#2E86AB'),
        spaceAfter=30,
        alignment=1  # Center
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#A23B72'),
        spaceAfter=12,
    )
    
    # Title
    title = Paragraph("OvaSense AI - PCOS Phenotype Report", title_style)
    story.append(title)
    story.append(Spacer(1, 0.3 * inch))
    
    # Report date
    date_text = f"Report Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}"
    story.append(Paragraph(date_text, styles['Normal']))
    story.append(Spacer(1, 0.3 * inch))
    
    # Classification Result Section
    story.append(Paragraph("Classification Result", heading_style))
    
    result_data = [
        ['Phenotype:', phenotype_result.phenotype],
        ['Confidence:', f"{phenotype_result.confidence:.1f}%"],
        ['Assessment Date:', symptom_log.created_at.strftime('%B %d, %Y')],
    ]
    
    result_table = Table(result_data, colWidths=[2*inch, 4*inch])
    result_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F4F4F4')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey),
    ]))
    
    story.append(result_table)
    story.append(Spacer(1, 0.3 * inch))
    
    # Symptom Data Section
    story.append(Paragraph("Symptom Data", heading_style))
    
    symptom_data = [
        ['Cycle Gap:', f"{symptom_log.cycle_gap_days} days"],
        ['BMI:', f"{symptom_log.bmi:.1f}"],
        ['Acne:', 'Yes' if symptom_log.acne else 'No'],
        ['Stress Level:', f"{symptom_log.stress_level}/10"],
        ['Sleep Hours:', f"{symptom_log.sleep_hours} hours"],
    ]
    
    symptom_table = Table(symptom_data, colWidths=[2*inch, 4*inch])
    symptom_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F4F4F4')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey),
    ]))
    
    story.append(symptom_table)
    story.append(Spacer(1, 0.3 * inch))
    
    # Key Factors Section
    story.append(Paragraph("Key Contributing Factors", heading_style))
    
    for i, reason in enumerate(phenotype_result.reasons, 1):
        reason_para = Paragraph(f"{i}. {reason}", styles['Normal'])
        story.append(reason_para)
        story.append(Spacer(1, 0.1 * inch))
    
    story.append(Spacer(1, 0.3 * inch))
    
    # Recommendations Section
    story.append(Paragraph("General Recommendations", heading_style))
    
    recommendations = get_recommendations(phenotype_result.phenotype)
    for rec in recommendations:
        rec_para = Paragraph(f"• {rec}", styles['Normal'])
        story.append(rec_para)
        story.append(Spacer(1, 0.1 * inch))
    
    story.append(Spacer(1, 0.5 * inch))
    
    # Disclaimer
    disclaimer_style = ParagraphStyle(
        'Disclaimer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.grey,
        leading=12,
    )
    
    disclaimer = Paragraph(
        "<b>Disclaimer:</b> This report is generated by an AI-based demo system for "
        "educational purposes only. It is not a medical diagnosis. Please consult "
        "with a qualified healthcare professional for proper medical advice.",
        disclaimer_style
    )
    story.append(disclaimer)
    
    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer


def get_recommendations(phenotype):
    """
    Get health recommendations based on phenotype.
    
    Args:
        phenotype (str): PCOS phenotype classification
        
    Returns:
        list: Recommendation strings
    """
    recommendations = {
        "Insulin Resistant PCOS": [
            "Consider a low glycemic index diet to manage insulin levels",
            "Regular exercise (30 minutes daily) can improve insulin sensitivity",
            "Consult with a healthcare provider about metabolic health assessment",
            "Monitor blood sugar levels regularly",
            "Consider stress management techniques like meditation or yoga"
        ],
        "Lean PCOS": [
            "Focus on nutrient-dense foods to maintain healthy weight",
            "Regular moderate exercise without excessive calorie restriction",
            "Monitor hormonal health with regular checkups",
            "Ensure adequate sleep (7-9 hours nightly)",
            "Consider supplements after consulting with healthcare provider"
        ],
        "Stress-Induced Irregularity": [
            "Prioritize stress management techniques (meditation, therapy, yoga)",
            "Establish a consistent sleep schedule",
            "Engage in regular physical activity to reduce stress",
            "Consider mindfulness practices",
            "Maintain work-life balance and set boundaries"
        ],
        "Moderate Risk": [
            "Monitor menstrual cycle patterns regularly",
            "Maintain a balanced, nutritious diet",
            "Regular exercise routine (mix of cardio and strength training)",
            "Schedule regular health checkups",
            "Track symptoms and discuss with healthcare provider"
        ],
        "Low Risk": [
            "Continue maintaining healthy lifestyle habits",
            "Regular health screenings as preventive care",
            "Balanced diet with variety of nutrients",
            "Stay physically active",
            "Monitor any changes in menstrual patterns"
        ]
    }
    
    return recommendations.get(phenotype, recommendations["Low Risk"])
